apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  namespace: {{ .Release.Namespace  }}
  {{- if .Values.service.annotations }}
  annotations:
{{ .Values.service.annotations | toYaml | indent 4}}
  {{- end }}
spec:
  selector:
    app: sc-pod
  ports:
    - name: https
      port: {{ .Values.service.port }}
      targetPort: https
    - name: sensor-port
      port: {{ .Values.service.sensorPort | default 8837 }}
      targetPort: sensor-port
  type: LoadBalancer
