apiVersion: v1
kind: Secret
metadata:
  annotations:
    {{- include "annotations" . | nindent 4 }}
    helm.sh/hook: post-delete
    helm.sh/hook-delete-policy: hook-failed,before-hook-creation,hook-succeeded
    helm.sh/hook-weight: "-1"
  labels:
    {{- include "labels" . | nindent 4 }}
  name: {{ .Release.Name }}-hook-post-delete
  namespace: {{ .Release.Namespace }}
stringData:
  API_KEY_TOKEN: {{ .Values.apiKeyToken }}
type: Opaque