apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  annotations:
    {{- include "annotations" . | nindent 4 }}
    helm.sh/hook: post-install, post-upgrade
    helm.sh/hook-delete-policy: before-hook-creation, hook-succeeded
    helm.sh/hook-weight: "-1"
  labels:
    {{- include "labels" . | nindent 4 }}
  name: {{ .Release.Name }}-hook-post-install
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Release.Name }}-hook-post-install
subjects:
- kind: ServiceAccount
  name: {{ .Release.Name }}-hook-post-install
  namespace: {{ .Release.Namespace }}