{{- if .Values.configureIdentity }}
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    {{- include "annotations" . | nindent 4 }}
  labels:
    {{- include "labels" . | nindent 4 }}
  name: {{ .Release.Name }}-identity
  namespace: {{ .Release.Namespace }}
{{- end }}