{{- if .Values.configureIdentity }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
    {{- include "annotations" . | nindent 4 }}
  labels:
    {{- include "labels" . | nindent 4 }}
  name: {{ .Release.Namespace }}:{{ .Release.Name }}-identity
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name:  {{ .Release.Namespace }}:{{ .Release.Name }}-identity
subjects:
- kind: ServiceAccount
  name: {{ .Release.Name }}-identity
  namespace: {{ .Release.Namespace }}
{{- end }}