{{- if .Values.configureNetwork }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    {{- include "annotations" . | nindent 4 }}
  labels:
    {{- include "labels" . | nindent 4 }}
  name: {{ .Release.Namespace }}:{{ .Release.Name }}-network
rules:
  - apiGroups: [""]
    resources: ["namespaces"]
    resourceNames: ["kube-system"]
    verbs: ["get"]
{{- end }}