configureIdentity: true
configureNetwork: true
containerImagePath: tenable/cloud-security-kubernetes-cluster-connector
containerImagePullSecrets: []
pod:
  affinity: {}
  annotations: {}
  labels: {}
  resources: {}
  tolerations: []
resourceNamePrefix: kubernetes-cluster-connector