{{- if and .Values.sensor.enabled (.Capabilities.APIVersions.Has "security.openshift.io/v1/SecurityContextConstraints") }}
apiVersion: security.openshift.io/v1
kind: SecurityContextConstraints
metadata:
  annotations:
    {{- include "annotations" . | nindent 4 }}
  labels:
    {{- include "labels" . | nindent 4 }}
    {{- include "sensor.labels" . | nindent 4 }}
  name: {{ include "sensor.globalResourceName" (dict "name" "scc" "root" .) }}
allowHostDirVolumePlugin: true
allowHostIPC: true
allowHostPID: true
allowHostPorts: true
allowPrivilegeEscalation: true
allowPrivilegedContainer: true
allowedCapabilities:
  - '*'
allowedUnsafeSysctls:
  - '*'
defaultAddCapabilities: null
fsGroup:
  type: RunAsAny
priority: null
readOnlyRootFilesystem: false
requiredDropCapabilities: null
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: RunAsAny
seccompProfiles:
  - '*'
supplementalGroups:
  type: RunAsAny
volumes:
  - '*'
users:
  - system:serviceaccount:{{ .Release.Namespace }}:{{ include "sensor.resourceNamePrefix" . }}-service-account
{{- end }}