{{- if .Values.sensor.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    {{- include "annotations" . | nindent 4 }}
  labels:
    {{- include "labels" . | nindent 4 }}
    {{- include "sensor.labels" . | nindent 4 }}
  name: {{ include "sensor.resourceNamePrefix" . }}-service-account
  namespace: {{ .Release.Namespace }}
{{- end }}