apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ .Release.Namespace }}-tes-deployment-assessment-issuer
  namespace: {{ .Release.Namespace }}
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Release.Namespace }}-tes-deployment-assessment-ca
  namespace: {{ .Release.Namespace }}
spec:
  isCA: true
  commonName: {{ .Release.Namespace }}-tes-deployment-assessment-ca
  secretName: {{ .Release.Namespace }}-tes-deployment-assessment-root-secret
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: {{ .Release.Namespace }}-tes-deployment-assessment-issuer
    kind: Issuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ .Release.Namespace }}-tes-deployment-assessment-ca-issuer
  namespace: {{ .Release.Namespace }}
spec:
  ca:
    secretName: {{ .Release.Namespace }}-tes-deployment-assessment-root-secret
