kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.name }}-role-binding
  namespace: {{ .Release.Namespace  }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.name }}-service-account
  namespace: {{ .Release.Namespace  }}
roleRef:
  kind: Role
  name: {{ .Values.name }}-role
  apiGroup: rbac.authorization.k8s.io
