apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.name }}
  name: {{ .Values.name }}
spec:
  type: ClusterIP
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: {{ .Values.name }}-tls
      port: 8091
      protocol: TCP
      targetPort: {{ .Values.service.https.containerPort }}
  selector:
    app.kubernetes.io/name: {{ .Values.name }}
