apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: {{ .Values.name }}-webhook.tenable.com
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/{{ .Values.name }}-webhook-cert
webhooks:
  - name: {{ .Values.name }}-webhook.tenable.com
    failurePolicy:  {{ .Values.validatingWebhook.failurePolicy }}
    namespaceSelector:
      matchExpressions:
      - key: kubernetes.io/metadata.name
        operator: NotIn
        values:
          - {{ .Release.Namespace }}
      {{- with .Values.validatingWebhook.excludeNamespaces }}
      {{- toYaml . | nindent 10 }}
      {{- end }}
      {{- with .Values.validatingWebhook.includeNamespaces }}
      - key: kubernetes.io/metadata.name
        operator: In
        values:
      {{- toYaml . | nindent 10 }}
      {{- end }}
    # namespaceSelector:
    #   matchLabels:
    #     admission-webhook: enabled
    rules:
      - apiGroups: [""]
        apiVersions: ["v1"]
        operations: ["CREATE","UPDATE"]
        resources: ["pods"]
        scope: "*"
    clientConfig:
      service:
        namespace: {{ .Release.Namespace }}
        name: {{ .Values.name }}
        path: {{ .Values.validatingWebhook.path }}
        port: {{ .Values.service.https.containerPort }}
    admissionReviewVersions: ["v1"]
    sideEffects: None
    timeoutSeconds:  {{ .Values.validatingWebhook.timeoutSeconds }}
