apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.name }}-webhook-cert
  namespace: {{ .Release.Namespace }}
spec:
  secretName: {{ .Values.name }}-webhook-tls
  dnsNames:
  - {{ .Values.name }}
  - {{ .Values.name }}.{{ .Release.Namespace }}
  - {{ .Values.name }}.{{ .Release.Namespace }}.svc
  - {{ .Values.name }}.{{ .Release.Namespace }}.svc.cluster.local
  issuerRef:
    {{- if .Values.useCustomCA }}
    name: {{ .Values.customCAIssuerName }}
    {{- else }}
    name: {{ .Release.Namespace }}-tes-deployment-assessment-ca-issuer
    {{- end }}
    kind: Issuer
