apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tenable-pvc-sc
  namespace: {{ .Values.namespace | default "tenable" }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistentVolumeClaim.size }}