apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  namespace: {{ .Release.Namespace  }}
  {{- if .Values.service.annotations }}
  annotations:
{{ .Values.service.annotations | toYaml | indent 4}}
  {{- end }}
spec:
  selector:
    app: sc-pod
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
  type: {{ .Values.service.type }}
