apiVersion: v1
kind: Secret
metadata:
  annotations:
    {{- include "annotations" . | nindent 4 }}
  labels:
    {{- include "labels" . | nindent 4 }}
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
stringData:
  API_KEY_TOKEN: {{ .Values.apiKeyToken }}
type: Opaque