name: Release Charts

on:
  push:
    branches:
      - test_releases
    paths:
      - 'charts/cloud-security/**'

jobs:
  release:
    # depending on default permission settings for your org (contents being read-only or read-write for workloads), you will have to add permissions
    # see: https://docs.github.com/en/actions/security-guides/automatic-token-authentication#modifying-the-permissions-for-the-github_token
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v4
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - name: Copy Existing releases
        run: |
          mkdir -p .cr-release-packages
          cp releases/*.tgz .cr-release-packages/

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.6.0
        with:
          config: .cr.yaml
          charts_dir: charts/cloud-security
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          CR_INDEX_PATH: ".cr-index/index.yaml"
          CR_PACKAGE_PATH: ".cr-release-packages"
          CR_SKIP_EXITING: "true"
          CR_PACKAGES_WITH_INDEX: "true"
          CR_RELEASE_NAME_TEMPLATE: "release/{{ .Name }}--{{ .Version }}"
